[package]
name = "cvss_vulnerability_scores"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
itertools = "0.10.5"
num = "0.4.0"
regex = "1.7.1"
